CREATE DATABASE IF NOT EXISTS relax_spa;
USE relax_spa;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'Receptionist',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);